
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokaci-infra-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pokaci-infra
  template:
    metadata:
      name: pokaci-infra
      labels:
        app: pokaci-infra
    spec:
      containers:
      - name: pokaci-infra
        image: emmylong1/ecommerce-app:latest
        ports:
        - containerPort: 5000
